server:
  shutdown: graceful
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: "default"
          uri: http://127.0.0.1:8081/
          predicates:
            - Host=**
          filters:
            - PreserveHostHeader

management:
  server:
    port: 18091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG